---
title: "Script4"
output: html_document
---

# Librairies

```{r Librairies}
#permet de gérer les gpkg
library(sf)
#permet de faire des maps
library(mapsf)
library(happign)
library(terra)
```

```{r Début}
insee <- st_read("insee.geojson")
nivdevie <- insee[,c(1:13)]
nivdevie <- nivdevie[,c(1,2,8,13,14)]
nivdevie$moy_niv <- nivdevie$ind_snv/nivdevie$pop_carr
```
```{r Hist}
hist(nivdevie$moy_niv)
```

```{r Summary}
summary(nivdevie$moy_niv)
```
```{r Quantiles}
nivdevie$indicateur <- nivdevie$moy_niv-22284
quantile <- quantile(nivdevie$indicateur, na.rm = T)
nivdevie$indicateur_rapport [nivdevie$indicateur < 0] <- "Niveaux de vie inférieur au coût de la vie" 
nivdevie$indicateur_rapport [nivdevie$indicateur > 0] <- "Niveaux de vie supérieur au coût de la vie" 
table(nivdevie$indicateur_rapport)
```
```{r Carte}
rapport2 <- aggregate(nivdevie  [, c("indicateur_rapport")], by = list(nivdevie$indicateur_rapport), length)
mf_map(rapport2, type = "typo", var = "Group.1", border= NA, leg_title = "")
```
